### ISSUE TITLE
Results are not good as yours on alphamatting.com

### ISSUE THREAD

**Issue by moiling** [yaksoy/AffinityBasedMattingToolbox#4]
Hi Professor Aksoy!
I am very interested in your research and thank you for your code. 
I have a problem now. 
Whether I use 'mattePostTrim' or not, the results of the test run on alphamatting.com are not as good as yours. Why is that?

**Comment by yaksoy** [comment]
This is a re-implementation. Please check the note about this in the paper website: yaksoy.github.com/ifm
